version: "3.0"

services:
  fastapi:
    container_name: "fastapi"
    volumes:
      - ./app:/app:cached
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    working_dir: /app
    tty: true
    ports:
      - 8080:80
    command: uvicorn main:app --reload --host 0.0.0.0 --port 80

