version: "3.0"

services:
  fastapi:
    container_name: "fastapi"
    volumes:
      - ./api:/api:cached
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    working_dir: /api
    tty: true
    ports:
      - 8080:80
    environment:
      DYNAMO_ENDPOINT: "http://dynamodb-local:8000"
      AWS_ACCESS_KEY_ID: "DUMMYIDEXAMPLE"
      AWS_SECRET_ACCESS_KEY: "DUMMYEXAMPLEKEY"
      AWS_DEFAULT_REGION: "ap-northeast-1"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 80

  dynamodb-local:
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    user: root
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath ./data
    ports:
      - 8000:8000
    volumes:
      - "./dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal


  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    container_name: dynamodb-admin
    environment:
      DYNAMO_ENDPOINT: http://dynamodb-local:8000

    ports:
      - 8001:8001
    depends_on:
      - dynamodb-local
